context:
  name: lietorch
  version: 1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - git: https://github.com/VSLAM-LAB/lietorch
    rev: 3e2695ddedb6f234510da4f1519d9861e5a1cd8e

build:
  number: 0
  skip: win or cuda_compiler == "None" or cuda_compiler_version != "12.6"

requirements:
  build:
    - ${{ compiler('cuda') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - cmake
    - make
    - pkg-config  
    - sysroot_linux-64                # [linux64]
    - ${{ cdt('libglvnd-egl') }}      # [linux]
    - ${{ cdt('libglvnd-devel') }}    # [linux]
    - ${{ cdt('mesa-libgl-devel') }}  # [linux]
    - ${{ cdt('mesa-libegl-devel') }} # [linux]
    - ${{ cdt('mesa-dri-drivers') }}  # [linux]
    - ${{ cdt('libselinux') }}        # [linux]
    - ${{ cdt('libxdamage') }}        # [linux]
    - ${{ cdt('libxfixes') }}         # [linux]
    - ${{ cdt('libxxf86vm') }}        # [linux]
    - ${{ cdt('libxext') }}           # [linux]
    - ${{ cdt('libxau') }}            # [linux]
    - ${{ cdt('libxcb') }}            # [linux]
    - xorg-libxext 
    - xorg-libx11 
    - xorg-libxfixes

  host:
    - pytorch-gpu
    - cuda-version=12.6
    - cuda-cudart-dev
    - cuda-crt
    - cudnn
    - libcusparse-dev
    - cuda-driver-dev
    - cuda-nvcc
    - cuda-nvrtc-dev
    - cuda-nvtx-dev
    - cuda-nvml-dev
    - cuda-profiler-api
    - cusparselt
    - libcublas-dev
    - libcudss-dev
    - libcufile-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - pip
    - python=3.11
    - setuptools
  run:
    - python=3.11
    - pytorch-gpu
    #- tqdm
    #- open3d
    - scipy
    #- opencv
    #- suitesparse
    #- matplotlib
    - pyyaml
    #- huggingface_hub
    #- torch-scatter

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The LieTorch library generalizes PyTorch to 3D transformation groups.
  description: |
    The LieTorch library generalizes PyTorch to 3D transformation groups. Just as torch.Tensor is a multi-dimensional matrix of scalar elements, lietorch.SE3 is a multi-dimensional matrix of SE3 elements. We support common tensor manipulations such as indexing, reshaping, and broadcasting. Group operations can be composed into computation graphs and backpropagation is automatically peformed in the tangent space of each element. For more details, please see our paper: Tangent Space Backpropagation for 3D Transformation Groups Zachary Teed and Jia Deng, CVPR 2021
  homepage: https://github.com/princeton-vl/lietorch
  
extra:
  authors:
    - Zachary Teed
    - Jia Deng
  recipe-maintainers:
    - fontan
