context:
  name: droidslam
  version: 1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - git: https://github.com/VSLAM-LAB/DROID-SLAM
    rev: 3b25784d4d260691737c47be199eacff57f7c989

build:
  number: 0
  skip: win or cuda_compiler == "None" or cuda_compiler_version != "12.6"
  script:
    - python -m pip install . --no-deps --no-build-isolation
    
requirements:
  build:
    - ${{ compiler('cuda') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - pkg-config  
    - cmake
    - make

  host:
    - python = 3.11
    - setuptools
    - pip
    # OpenGL
    - libgl-devel
    - libegl-devel
    - libglvnd-devel
    - libopengl-devel
    # X11
    - xorg-libxext
    - xorg-libx11
    - xorg-libxfixes
    - xorg-libxrender
    - xorg-libice
    - xorg-libsm
    - xorg-libxdmcp
    - xorg-libxau
    - xorg-xorgproto
    - libxkbcommon
    # CUDA Build Tools
    - cuda-version ==${{ cuda_compiler_version }}
    - cuda-cudart-dev
    - cuda-crt
    - libcusparse-dev
    - cuda-driver-dev
    - cuda-nvcc
    - cuda-nvrtc-dev
    - cuda-nvtx-dev
    - cuda-nvml-dev
    - cuda-profiler-api
    # CUDA Libraries
    - cudnn
    - libcublas-dev
    - libcudss-dev
    - libcufile-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - cusparselt
    - libnvjitlink
    # Torch libraries
    - pytorch-gpu
    - fontan::lietorch
    
  run:
    - python=3.11
    - pytorch-gpu
    - tqdm
    - open3d
    - scipy
    - opencv
    - suitesparse
    - matplotlib
    - pyyaml
    - huggingface_hub
    - torch-scatter
    - fontan::lietorch

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Deep Visual SLAM for Monocular, Stereo, and RGB-D Cameras
  description: |
    This repo currently provides a single GPU implementation of our monocular, stereo, and RGB-D SLAM systems. It currently contains demos, training, and evaluation scripts.
  homepage: https://github.com/princeton-vl/DROID-SLAM

extra:
  authors:
    - Zachary Teed
    - Jia Deng
  recipe-maintainers:
    - fontan
