context:
  name: gtsam
  version: 1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: https://github.com/borglab/gtsam.git
  rev: 90f6f33f6c015e4227f927f6af7b356fe0930809
  patches:
    - nobuild-examples-timing.patch
    # - unvendor-findtbb.patch
    # - unvendor-pybind11.patch
    # - fix-python-build-win.patch  # [win]
    # - fix-boost.patch  # [win]
    # - fix-osx-rpath.patch  # [osx]
    # - 1553_1584.patch
    # - include_bitset.patch
    # - fix-gtsam-export-4.2.0.patch
    # - fix-gtsam-unstable-export-4.2.0.patch
    # - fix-missing-includes.patch
    # - windows_python_fix_part_of_pr1685.patch

# build:
#   number: 14
#   run_exports:
#     - '{{ pin_subpackage(name, max_pin="x.x") }}'

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - ninja
    - cmake
    - pybind11                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    #- cross-python_${{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - libboost-devel
    - eigen
    - geographiclib-cpp
    - metis
    - suitesparse
    - tbb
    - tbb-devel
    - pybind11
    - pyparsing
    - numpy
    - setuptools
    - pip
  run:
    - python
    - pyparsing
    - numpy

# test:
#   files:
#     - regression_test_25.py
#   commands: 
#     - python regression_test_25.py  # [build_platform == target_platform]
#     - test -f ${PREFIX}/lib/libgtsam${SHLIB_EXT}  # [not win]
#     - test -f ${PREFIX}/lib/cmake/gtwrap/gtwrapConfig.cmake  # [not win]
#     - test -f ${PREFIX}/lib/cmake/GTSAM/GTSAMConfig.cmake  # [not win]
#     - test -f ${PREFIX}/include/gtsam/base/types.h  # [not win]
#     - if exist %PREFIX%\\Library\\include\\gtsam\\base\\types.h (exit 0) else (exit 1)  # [win]
#     - if exist $PREFIX$\\Library\\lib\\gtsam.lib (exit 0) else (exit 1)  # [win]
#     - if exist $PREFIX$\\Library\\bin\\gtsam.dll (exit 0) else (exit 1)  # [win]
#   imports:
#     - gtsam


about:
  homepage: https://github.com/borglab/gtsam
  summary: GTSAM is a library of C++ classes that implement smoothing and mapping (SAM) in robotics and vision
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE.BSD

extra:
  recipe-maintainers:
    - fontan