context:
  name: vggtslam-vslamlab
  version: 1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - git: https://github.com/VSLAM-LAB/VGGT-SLAM-VSLAM-LAB
    rev: db1698e78bc246f15f1fd6581d6a16d2a154b434

build:
  number: 0
  skip: win or cuda_compiler == "None" or cuda_compiler_version != "12.6"

requirements:
  build:
    - ${{ compiler('cuda') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - cmake < 4
    - make
    - pkg-config  

  host:
    # Python & Build Tools
    - python = 3.11
    - setuptools
    - pip
    - pybind11

    # Python core + DL
    - fontan::pangolin
    - fontan::pypose
    - pytorch-gpu
    - torchvision
    - pytorch_scatter
    - numba
    - numpy
    - tqdm
    - einops   
    - kornia    
    - opencv
    - yacs
    - eigen

    # CUDA Toolkit Libraries
    - cuda-version = ${{ cuda_compiler_version }}
    - cuda-cudart-dev
    - cuda-crt
    - cudnn
    - libcusparse-dev
    - cuda-driver-dev
    - cuda-nvcc
    - cuda-nvrtc-dev
    - cuda-nvtx
    - cuda-nvtx-dev
    - cuda-nvml-dev
    - cuda-profiler-api
    - cusparselt
    - libcublas-dev
    - libcudss-dev
    - libcufile-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libnvjitlink

    # Logging / Evaluation
    - tensorboard
    - plyfile
    - evo

    - Pillow
    - huggingface_hub
    - safetensors
    - hydra-core
    - omegaconf
    - scipy
    - onnxruntime
    - requests
    - trimesh
    - matplotlib
    - gradio
    - viser
    - open3d
    - pytorch-metric-learning
    - pytorch-lightning
    - termcolor
    - virtualenv >=20.10.0
    - lz4
    - fontan::gtsam

  run:
    - torchvision
    - pytorch_scatter 
    - opencv 
    - evo
    - yacs
    - einops 
    - numba
    - tqdm
    - viser
    - termcolor

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: VGGT-SLAM
  homepage: https://github.com/MIT-SPARK/VGGT-SLAM

extra:
  authors:
    - Dominic Maggio
    - Hyungtae Lim
    - Luca Carlone
  recipe-maintainers:
    - fontan
