#{% set version = "2.2.0" %}
#{% set processor = "cpu" if (cuda_compiler_version or "None") == "None" else "gpu" %}

# Prioritize gpu build if cudatoolkit can be installed (through __cuda virtual package)
#{% set build = 8 %}
#{% set build = build + 100 if processor == "gpu" else build %}

context:
  name: ceres-solver
  version: 1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

#source:
#  url: http://ceres-solver.org/ceres-solver-{{ version }}.tar.gz
#  sha256: 0c70ed3a1a2d6ba47c06c7e8b3b040880bc474db

source:
  - git: https://github.com/ceres-solver/ceres-solver
    rev: 0c70ed3a1a2d6ba47c06c7e8b3b040880bc474db

build:
  number: 0
  skip: win or cuda_compiler == "None" or cuda_compiler_version != "12.6"
  script:
    - ./build.sh

# build:
#   number: 0
#   string: ${{ processor }}h{{ PKG_HASH }}_{{ build }}
  #skip: true  # [cuda_compiler_version == "11.8"]
  #run_exports:
  #  - ${{ pin_subpackage('ceres-solver', max_pin='x.x') }}
  #  - ${{ pin_compatible('eigen', max_pin='x.x.x') }}
  #ignore_run_exports_from:
  #  - libblas

requirements:
  build:
    - ${{ compiler('cuda') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - pkg-config  
    - cmake
    - make
  host:
    - glog
    # cmake find_package(LAPACK) needs blas
    # even though it's not linked
    - libblas
    - liblapack
    - metis
    #- suitesparse (disable because GPL: https://github.com/ceres-solver/ceres-solver/issues/1026)
    - eigen
    - libcublas-dev                             # [(cuda_compiler_version or "None").startswith("12")]
    - libcusolver-dev                           # [(cuda_compiler_version or "None").startswith("12")]
    - libcusparse-dev                           # [(cuda_compiler_version or "None").startswith("12")]
    - cuda-cudart-dev                           # [(cuda_compiler_version or "None").startswith("12")]
    - cuda-version ==${{ cuda_compiler_version }}  # [(cuda_compiler_version or "None").startswith("12")]
    # X11
    - xorg-libxext
    - xorg-libx11
    - xorg-libxfixes
    - xorg-libxrender
    - xorg-libice
    - xorg-libsm
    - xorg-libxdmcp
    - xorg-libxau
    - xorg-xorgproto
    - libxkbcommon
    # CUDA Build Tools
    - cuda-version ==${{ cuda_compiler_version }}
    - cuda-cudart-dev
    - cuda-crt
    - libcusparse-dev
    - cuda-driver-dev
    - cuda-nvcc
    - cuda-nvrtc-dev
    - cuda-nvtx-dev
    - cuda-nvml-dev
    - cuda-profiler-api
    # CUDA Libraries
    - cudnn
    - libcublas-dev
    - libcudss-dev
    - libcufile-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - cusparselt
    - libnvjitlink
  run:
    - eigen
    #- ${{ pin_compatible('eigen', max_pin='x.x.x') }}
    #- __cuda >={{ cuda_compiler_version }}      # [cuda_compiler_version != "None"]

# test:
#   requires:
#     - ${{ compiler('cuda') }}
#     - ${{ compiler('cxx') }}
#     - ${{ compiler('c') }}
#     - ${{ stdlib('c') }}
#     - pkg-config  
#     - cmake
#     - make
#   files:
#     - tests/
#   source_files:
#     - examples/helloworld.cc
#   commands:
#     - test -f ${PREFIX}/include/ceres/ceres.h  # [unix]
#     - test -f ${PREFIX}/lib/libceres${SHLIB_EXT}  # [unix]
#     - if not exist %PREFIX%\\Library\\include\\ceres\\ceres.h exit 1  # [win]
#     - if not exist %PREFIX%\\Library\\lib\\ceres.lib exit 1  # [win]
#     - if not exist %PREFIX%\\Library\\bin\\ceres.dll exit 1  # [win]

# about:
#   home: http://ceres-solver.org
#   license: BSD-3-Clause
#   license_file: LICENSE
#   summary: A large scale non-linear optimization library

# extra:
#   recipe-maintainers:
#     - jschueller
#     - seanyen
#     - hobu
