context:
  name: orbslam2-vslamlab
  version: 1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - git: https://github.com/VSLAM-LAB/ORB-SLAM2-VSLAM-LAB
    rev: 053f26faded2f824ff5297a09fa5a03e19c1a4ae

build:
  number: 0
  skip: win
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - cmake
    - make
    - pkg-config  
  host:
    - libgl-devel
    - libegl-devel
    - libglvnd-devel
    - libopengl-devel
    - xorg-libxext
    - xorg-libx11
    - xorg-libxfixes
    - xorg-libxrender
    - xorg-libice
    - xorg-libsm
    - xorg-libxdmcp
    - xorg-libxau
    - eigen >=3.4.0,<3.5.0
    - yaml-cpp
    - opencv >=4.10.0,<5 
    - fontan::pangolin
  run:
    - eigen >=3.4.0,<3.5.0
    - yaml-cpp
    - opencv >=4.10.0,<5
    - fontan::pangolin

about:
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: ORB-SLAM2 is a real-time SLAM library for Monocular, Stereo and RGB-D cameras. 
  homepage: https://github.com/raulmur/ORB_SLAM2

extra:
  authors:
    - Raul Mur-Artal
    - Juan D. Tardos
    - J. M. M. Montiel
    - Dorian Galvez-Lopez
  recipe-maintainers:
    - fontan
