context:
  name: orbslam3-vslamlab
  version: 1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - git: https://github.com/VSLAM-LAB/ORB_SLAM3_VSLAM_LAB
    rev: 553dd0896a6f29212d5c832647d56bb7dc6cf820

build:
  number: 0
  skip: win
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja >=1.12.1,<1.13
    - cmake >=3.31.1,<3.32
    - make
    - pkg-config >=0.29.2,<0.30
  host:
    - libgl-devel
    - libegl-devel
    - libglvnd-devel
    - libopengl-devel
    - xorg-libxext
    - xorg-libx11
    - xorg-libxfixes
    - xorg-libxrender
    - xorg-libice
    - xorg-libsm
    - xorg-libxdmcp
    - xorg-libxau
    - eigen >=3.4.0,<3.5.0
    - yaml-cpp
    - opencv >=4.10.0,<5 
    - fontan::pangolin
    - boost
  run:
    - eigen >=3.4.0,<3.5.0
    - yaml-cpp
    - opencv >=4.10.0,<5
    - fontan::pangolin
    - boost
about:
  license: GPL-3.0-only
  license_file: LICENSE
  summary: ORB-SLAM3 is the first real-time SLAM library able to perform Visual, Visual-Inertial and Multi-Map SLAM with monocular, stereo and RGB-D cameras, using pin-hole and fisheye lens models.
  homepage: https://github.com/UZ-SLAMLab/ORB_SLAM3

extra:
  authors:
    - Carlos Campos
    - Richard Elvira
    - Juan J. Gómez Rodríguez
    - J. M. M. Montiel
    - Juan D. Tardos
  recipe-maintainers:
    - fontan
